version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pms-backend:latest
    container_name: pms-backend
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
